### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by RiseT** [cryptomator/sanitizer#4] opened 2017-10-26 14:41 UTC
- When trying to use Sanitizer without a passphrase file, I **cannot paste my passphrase** into PowerShell (and my passphrase is rather long and complex, manually typing is not really an option).
- When trying to use a **passphrase file** instead with the passphrase in it, I'm getting the following exception.

Edit: Actually, the cursor doesn't move at all or show anything when trying to type the passphrase manually. Is that by design? And it seems like pasting the passphrase does work, but there's no visual feedback at all.

# Cryptomator vault sanitizer v0.14 #

```
Exception in thread "main" java.lang.IndexOutOfBoundsException
        at sun.nio.cs.StreamDecoder.read(Unknown Source)
        at java.io.InputStreamReader.read(Unknown Source)
        at org.cryptomator.sanitizer.commands.CheckCommand.passphraseFromFile(CheckCommand.java:189)
        at org.cryptomator.sanitizer.commands.CheckCommand.passphrase(CheckCommand.java:161)
        at org.cryptomator.sanitizer.commands.CheckCommand.parse(CheckCommand.java:130)
        at org.cryptomator.sanitizer.commands.Commands.<init>(Commands.java:61)
        at org.cryptomator.sanitizer.commands.Commands.parse(Commands.java:26)
        at org.cryptomator.sanitizer.Sanitizer.main(Sanitizer.java:12)
```

**Comment by tobihagemann** [comment] 2017-11-25 11:00
As far as I know, the password is read via Java's [`System.console().readPassword("...")`](https://docs.oracle.com/javase/8/docs/api/java/io/Console.html#readPassword--):

> Provides a formatted prompt, then reads a password or passphrase from the console with echoing disabled.

That the cursor is not moving at all is indeed by design. It's a convention in command-line tools that the visual feedback is missing (echoing is disabled). I guess to prevent someone else seeing how long the password is.

I don't know why you can't paste the passphrase in PowerShell. But the fact that you're unable to use a passphrase file, looks like a bug. I'm able to reproduce the issue. @markuskreusch Can you please have a look at it?

**Comment by RiseT** [comment] 2018-11-13 12:21
Is this issue fixed by https://github.com/cryptomator/sanitizer/commit/8a7514deab88b1d4c7a61cfcc825f3f9d8463f2e ?

**Comment by tobihagemann** [comment] 2018-11-13 12:23
Oh yes, should be fixed in 0.15. Feel free to reopen the issue if you're still experiencing issues.

**Closed as completed by tobihagemann** 2018-11-13 12:23 UTC
Labels: bug

**Comment by RiseT** [comment] 2018-11-13 12:28
@tobihagemann Thanks! Off-topic: Does v1.4 convert/upgrade the database (edit: database = vault)?

**Comment by tobihagemann** [comment] 2018-11-13 12:33
Nope, vault format stayed the same with Cryptomator 1.4. :)
